
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.Timer;
import java.util.TimerTask;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sami
 */
public class Controller extends javax.swing.JFrame {

    /**
     * Creates new form Controller
     * 
     */
     private final Deck Deck0=new Deck();
    private final Dealer Dealer0=new Dealer();
    private final Player Player0=new Player();
    public Controller() {
        initComponents();
 
         jPanel1.remove(jLabel2);
         jPanel1.remove(jLabel5);
         jPanel1.remove(jLabel3);
         jPanel1.remove(jLabel6);
         jPanel1.remove(jLabel1);
         
       
        
         jLabel5.setLocation(jLabel1.getLocation().x,jLabel1.getLocation().y);
         jLabel3.setLocation(jLabel1.getLocation().x,jLabel1.getLocation().y);
         jLabel2.setLocation(jLabel1.getLocation().x,jLabel1.getLocation().y);
         jLabel6.setLocation(jLabel1.getLocation().x,jLabel1.getLocation().y);
         jLabel1.setLocation(jLabel1.getLocation().x,jLabel1.getLocation().y);
         
        
          String w="Cards/"+ "BRH"+".png";
          ImageIcon image = new ImageIcon(w);
          jLabel1.setSize(72, 96);
          jLabel1.setIcon(image);
                
                
         jPanel1.add(jLabel1);  
         jPanel1.add(jLabel6);
         jPanel1.add(jLabel5);
         jPanel1.add(jLabel3);
          jPanel1.add(jLabel2);
         
      
         this.getContentPane().removeAll();
         jButton2.setVisible(false);
       this.getContentPane().add(jPanel1);
       
        this.repaint();
      
       this.revalidate();
       this.setResizable(false);
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jLabel4.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));

        jButton1.setText("StartNewGame");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jButton2.setText("Hit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Black Jack Game");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.getAccessibleContext().setAccessibleName("jButtonNewGame");
        jLabel1.getAccessibleContext().setAccessibleName("jLabelDeck");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
                this.Deck0.ResetCards();
		this.Deck0.ShuffleCards();
		this.Player0.GetCard(Deck0.getnextCard());
		this.Dealer0.GetCard(Deck0.getnextCard());
		this.Player0.GetCard(Deck0.getnextCard());
		this.Dealer0.GetCard(Deck0.getnextCard());
        
                Card[] DealerHand=Dealer0.getCurrentCards();
                 Card[] PlayerHand=Player0.getCurrentCards();
                 
                String w="Cards/"+ DealerHand[0].getName()+".png";
                  ImageIcon image = new ImageIcon(w);
               jLabel2.setSize(72, 96);
                jLabel2.setIcon(image);
                 w="Cards/"+ "BRH"+".png";
                   image = new ImageIcon(w);
                  jLabel3.setSize(72, 96);
                 jLabel3.setIcon(image);  
                    w="Cards/"+ PlayerHand[0].getName()+".png";
                   image = new ImageIcon(w);
        
                   jLabel5.setSize(72, 96);
                 jLabel5.setIcon(image);
                   
                 w="Cards/"+ PlayerHand[1].getName()+".png";
                   image = new ImageIcon(w);
                   jLabel6.setSize(72, 96);
                 jLabel6.setIcon(image);
                 
                MoveCrossCard(jLabel2,0);
                MoveVerticalCard(jLabel2,1000,30);
                
                MoveCrossCardP(jLabel5,2000);
                MoveVerticalCard(jLabel5,3000,35);
                
                
                MoveCrossCard(jLabel3,4000);
                MoveVerticalCard(jLabel3,5000,25);
                
               
                
                MoveCrossCardP(jLabel6,6000);
                MoveVerticalCard(jLabel6,7000,30);
                
                
              
             
                Timer time1=new Timer();
                
                TimerTask task=new TimerTask()
                {
                    int counter=0;
                    public void run()
                    {
                        if(counter==1)
                        {
                            time1.cancel();
                            
                        }
                             jButton1.setVisible(false);
                             jButton2.setVisible(true);
                 
                        counter++;
                    }
                };
                time1.scheduleAtFixedRate(task, 7800, 30);
           
                 

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void MoveCrossCard(JLabel LabelC,int Delay)
    {
                Timer time1=new Timer();
                TimerTask task=new TimerTask()
                {
                    int counter=0;
                    public void run()
                    {
                        if(counter==30)
                        {
                            time1.cancel();
                            
                        }
                        LabelC.setLocation(LabelC.getLocation().x-5, LabelC.getLocation().y-5);
                        counter++;
                    }
                };
                time1.scheduleAtFixedRate(task, Delay, 30);
        
    }
    public void MoveCrossCardP(JLabel LabelC,int Delay)
    {
                Timer time1=new Timer();
                TimerTask task=new TimerTask()
                {
                    int counter=0;
                    public void run()
                    {
                        if(counter==25)
                        {
                            time1.cancel();
                            
                        }
                        LabelC.setLocation(LabelC.getLocation().x-5, LabelC.getLocation().y+5);
                        counter++;
                    }
                };
                time1.scheduleAtFixedRate(task, Delay, 30);
        
    }
    
    public void MoveVerticalCard(JLabel LabelC,int Delay,int limit)
    {
                Timer time1=new Timer();
                TimerTask task=new TimerTask()
                {
                    int counter=0;
                    public void run()
                    {
                        if(counter==limit)
                        {
                            time1.cancel();
                            
                        }
                        LabelC.setLocation(LabelC.getLocation().x-5, LabelC.getLocation().y);
                        counter++;
                    }
                };
                time1.scheduleAtFixedRate(task, Delay, 30);
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          lastLocation=120;
        
         
    }//GEN-LAST:event_jButton2ActionPerformed
  private int q=20;
  private int q2=10;
  

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Controller().setVisible(true);
               
                 
            }
        });
       
        
    }

    private int lastLocation=150;
    private Timer Time1;
    private Timer Time2;
    private String l;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
